name: show_update_dialog
description: Este pacote tem como objetivo ajudar a manter aplicativos Android e IOS atualizados,
version: 1.0.10
homepage: https://github.com/marcelo380/show_update_dialog/
environment:
  sdk: ">=2.16.0 <3.0.0"
  

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^1.4.2
  http: ^0.13.4
  html: ^0.15.0
  url_launcher: ^6.1.2
  collection: ^1.15.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - resources/download.png
