name: show_update_dialog
description: Este pacote tem como objetivo ajudar a manter aplicativos Android e IOS atualizados,
version: 1.0.4
homepage: https://github.com/marcelo380/show_update_dialog/
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^1.0.3
  http: ^0.13.3
  html: ^0.15.0
  url_launcher: ^6.0.9
  collection: ^1.15.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - resources/download.png
